### ISSUE TITLE
GET entities/:uuid returns 304 after resolve

### ISSUE THREAD

**Issue by sadiqkhoja** [getodk/central-backend#1041]
Currently we are using Entity `version` as ETag, however on `entity.resolve` we don't increment the version number hence `GET entities/:uuid` returns 304 Not Modified. 

Possible solution: Use hash(coalesce(updatedAt, createdAt)) as ETag

aux: change the http code of `entityVersionConflict` to 412 
> If the conditional does not match then the [412](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/412) (Precondition Failed) response is returned.

**Comment by matthew-white** [comment]
Couple of questions just to make sure I understand:

- Why does that endpoint return an ETag? Is it because of our use of the If-Match header?
- If the ETag changes, will we also need to change our use of the If-Match header?

By the way, I've also filed getodk/central#544, which seems thematically related. The two issues might end up being pretty separate though.

**Comment by sadiqkhoja** [comment]
that's right. Maybe etag is not required at all for `GET /entities/:uuid` because from frontend we are manually setting If-Match header

**Comment by matthew-white** [comment]
I didn't realize this right away, but this issue is user-facing:

- Navigate to the entity detail page for an entity with a conflict.
- Mark the entity as resolved.
- Refresh the page. The conflict summary box is still shown.

**Comment by matthew-white** [comment]
Decisions:

- Specify the `baseVersion` in the request body rather than using an ETag at all. We don't document the ETag header in the API docs currently, so this isn't a breaking change.
  - Frontend will need to specify this.
- Don't return a bespoke ETag (just the one that Express generates).

Document:

- When you do a patch to update an entity via the API, you can specify whether you want to the conflict (`?resolve`). The API will reject if there is no conflict.
- Without `?resolve=true`, an update after a concurrent conflict dismissal will be accepted.

**Comment by lognaturel** [comment]
I agree, @matthew-white, a query parameter does feel more expected.
