### ISSUE TITLE
Add ability to filter OData subtables

### ISSUE THREAD

**Issue by matthew-white** [getodk/central-backend#391]
Filing an issue in relation to this forum post by @mathieubossaert: https://forum.getodk.org/t/propagate-submission-date-to-child-tables/34349

Right now it's possible to filter the primary OData table using the `$filter` query parameter. However, it's not possible to filter subtables:

https://github.com/getodk/central-backend/blob/f16636d69e4c9869debe43b2ab8f73b3543d9929/lib/util/db.js#L235-L245

What's the best way in OData to enable subtable filtering? In terms of OData syntax, is a subtable allowed to reference fields in the primary table?

**Comment by matthew-white** [comment]
Linking to a new forum topic about filtering subtables: https://forum.getodk.org/t/using-filter-with-repeat-tables-to-download-odata/36245

**Comment by lognaturel** [comment]
I just got an ask for this.

**Comment by matthew-white** [comment]
> if the objective here is just to build ETL &hellip; then we already have a sleek way to do that including filtering subtables: combine `$expand` and `$filter`

I agree that that combination is super helpful and probably meets many users' needs. In the second forum topic above, that option was mentioned, but Odil said that they want to download each table separately for some reason. My hunch is that there's a valid use case in this area. @lognaturel, for the case that you mentioned, do you think `$expand` + `$filter` would be enough?

In terms of the three options above, option 3 with `$root` seems very elegant to me!

**Comment by lognaturel** [comment]
> do you think $expand + $filter would be enough

I think being able to filter each table independently would be preferable. Sometimes each table goes through a different process or some tables are completely unnecessary for some part of analysis. In those cases, it can be really annoying to have to deal with all data, especially if there are large numbers of submissions. For a concrete example, sometimes the form design pulls values from the top level into repeats so that the top level is unnecessary. In that case it’s a lot more convenient to only pull the repeat and not have to deal with the top level at all. 

> option 3 with $root seems very elegant to me!

I agree!
