### ISSUE TITLE
PUT .../submissions/:instanceId does not return expected fields

### ISSUE THREAD

**Issue by matthew-white** [getodk/central-backend#417]
When I send a PUT request to edit a submission using the REST API, I receive the following response:

```json
{
  "instanceId": "4bfcb0f9-7bb7-4bda-a165-ab731fbcaffc",
  "submitterId": 16,
  "createdAt": "2021-10-18T18:39:10.064Z",
  "instanceName": "White-Matt-9435bee7-c929-497e-874a-61a2f47389e4",
  "current": true
}
```

However, the schema of this JSON differs from what's normally returned for submissions:

- `current` usually isn't returned.
- Other fields usually are returned, including `deviceId` and `reviewState`.

**Comment by ktuite** [comment]
Closing this issue because we have determined that this PUT response is consistent with what is returned when fetching a specific version of a submission. It does not have all the information of a full Submission, but it does have the info of what the code internally calls a `Submission.Def`, essentially a snapshot of a submission for a particular version. Opening a new issue #481 to fix the docs. 

```javascript
"PUT /v1/projects/1/forms/simple/submissions/one HTTP/1.1"
{
  instanceId: 'two',
  submitterId: 6,
  createdAt: '2022-05-06T17:17:46.990Z',
  instanceName: null,
  current: true,
  deviceId: null,
  userAgent: 'node-superagent/3.8.3'
}
```

```javascript
"GET /v1/projects/1/forms/simple/submissions/one/versions/two HTTP/1.1" 200 162
{
  submitterId: 6,
  createdAt: '2022-05-06T17:00:49.002Z',
  instanceName: null,
  instanceId: 'two',
  current: true,
  deviceId: null,
  userAgent: 'node-superagent/3.8.3'
}
```
