### ISSUE TITLE
Add linting to CI and/or test targets?

### ISSUE THREAD

**Issue by alxndrsn** [getodk/central-backend#505]
This has been opened before at https://github.com/getodk/central-backend/issues/14.

Currently `eslint` is not run by any of the test-related make targets, or on CircleCI.  Would it be helpful to include it?  It should be an even quicker test/fail than running `mocha` tests, so adding it as a dependency to the `test` and `test-full` targets could be helpful.

**Comment by matthew-white** [comment]
We run the linter in CircleCI for Frontend, and I think that's worked well for us: that setup has been successful in catching things. I'd support adding linting to CircleCI on Backend. @ktuite, what do you think?

I feel less sure about having test-related make targets also lint: the two things feel somewhat separate to me. Then again, maybe that'd be a good way to ensure that we're consistent about both testing and linting. And with #503, linting will often be quite speedy. I could go either way! @ktuite, do you have a preference?

**Comment by alxndrsn** [comment]
> I feel less sure about having test-related make targets also lint: the two things feel somewhat separate to me.

I see `eslint` as a tool for testing the correctness of the code in the same way that `mocha` is.  From this perspective, there are 3 stages of testing:

1. lint
2. unit
3. integration

**Comment by matthew-white** [comment]
I could see that! I also had the thought that we could add a new command to do both, something like `lint-and-test`. But that probably doesn't make sense given that we have a few different test commands: we wouldn't want to have a separate `lint-and-test` command corresponding to each of those.

Actually, thinking of those different test commands, I'm realizing that one is specifically for unit tests and one is for integration tests. Since those two each correspond to an individual stage in your list, maybe it makes sense for them to continue to be independent. Specifically, I'm thinking that `test-unit` and `test-integration` shouldn't also lint (and `test-integration` shouldn't run `test-unit`). But I could see the case for the more expansive `test` and `test-full` commands also linting.

One other variable to throw in here is that Frontend also separates linting and testing, and I think it'd be harder there to combine the two. Would it be confusing if running tests lints in Backend but doesn't in Frontend? But Frontend also doesn't use a makefile — it uses package.json + Vue CLI — so maybe Frontend and Backend are already different enough in this area that there wouldn't be much confusion.
