### ISSUE TITLE
make migrations & make check-migrations exit cleanly when migration directory is corrupt

### ISSUE THREAD

**Issue by alxndrsn** [getodk/central-backend#509]
Commit: 0a1a59bf339cb6a498c350c6f9043e82a163794f
Node version: `v14.19.3`

I'd expect a target called `check-migrations` should be exiting with a non-zero code if it fails, but in this instance that doesn't seem to be the case.

## Steps to recreate

```
rm lib/model/migrations/20170920-01-initial.js
make check-migrations
```

## Example
```
$ make check-migrations; echo "Exited with status: $?"
node -e 'const { withDatabase, checkMigrations } = require("./lib/model/migrate"); withDatabase(require("config").get("default.database"))(checkMigrations);'
(node:769870) UnhandledPromiseRejectionWarning: Error: The migration directory is corrupt, the following files are missing: 20220627-01-add-random-counter.js
    at validateMigrationList (/x/odk/central-backend/node_modules/knex/lib/migrate/Migrator.js:575:11)
    at Migrator.list (/x/odk/central-backend/node_modules/knex/lib/migrate/Migrator.js:290:7)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:769870) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:769870) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Exited with status: 0
```

# `make migrations`

This target also fails but exits with `0` if there are migrations missing:

```
$ make migrations
node -e 'const { withDatabase, migrate } = require("./lib/model/migrate"); withDatabase(require("config").get("default.database"))(migrate);'
(node:71825) UnhandledPromiseRejectionWarning: Error: The migration directory is corrupt, the following files are missing: 20170920-01-initial.js, 20220627-01-add-random-counter.js
    at validateMigrationList (/x/odk/backend/node_modules/knex/lib/migrate/Migrator.js:575:11)
    at Migrator.latest (/x/odk/backend/node_modules/knex/lib/migrate/Migrator.js:70:7)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:71825) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:71825) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
$ echo $?
0
```

**Comment by matthew-white** [comment]
`check-migrations` is supposed to exit with a nonzero code if the migrations aren't right! You can see it trying to do that here:

https://github.com/getodk/central-backend/blob/0a1a59bf339cb6a498c350c6f9043e82a163794f/lib/model/migrate.js#L28-L34

If I'm remembering correctly, we don't use the makefile anywhere in production. Instead, the server is started using this script:

https://github.com/getodk/central/blob/master/files/service/scripts/start-odk.sh

Given how that script works, my instinct is that if we think `checkMigrations()` might fail without setting a nonzero code, we should modify `checkMigrations()` rather than the makefile. Specifically, we could catch an error thrown by `db.migrate.list()`. That said, it also seems pretty unlikely that `db.migrate.list()` would throw an error in production: something else would have to go wrong I think.

Given that we don't use the makefile in production, I'm not sure that it's super important that those commands set a nonzero code. But maybe in some workflows it'd be helpful. (It certainly wouldn't hurt!)

**Comment by alxndrsn** [comment]
> Given that we don't use the makefile in production, I'm not sure that it's super important that all commands set a nonzero code.

Great point!  I'll dig in and see if I can fix the underlying problem in the script.

**Comment by alxndrsn** [comment]
Issue updated to include details of `make migrations` behaviour.
