### ISSUE TITLE
Creating form draft results in 504 when there are many form fields

### ISSUE THREAD

**Issue by matthew-white** [getodk/central-backend#662]
@lognaturel was working on a server with a large number of form versions and hundreds of thousands of rows in the `form_fields` table. Quoting @lognaturel from Slack:

> Creating a form draft takes a very long time and sometimes 504s. This is for any form on the server. Publishing a form draft generally 504s.

The strong suspicion is that the `check_field_collisions` trigger is responsible:

> I can get things snappier by deleting all the form_field entries that correspond to the form with many versions except for the one for the active form def.

> The behavior I’m experiencing is exactly what @matthew-white described at #381. So I think the now-reverted change to the trigger made it so slow the problem would show up with fewer versions.

Two ideas for improvement:

> I believe that there are improvements to make to that trigger. There actually is a `formId` column on that table so it seems like at the very least the slowness could be constrained to only forms with many versions rather than affecting everything on the server.
> (and compounding if there are many forms with lots of versions)

> I wonder whether we could detect when the form schema hasn’t changed at all.
> Seems there are lots of cases in which we’re saving a LOT of duplicate data.

**Comment by lognaturel** [comment]
Discussed this briefly with the team. The underlying user need is scripting form attachment updates. This automates entity-based workflows.

One question was whether this is worth addressing given that we're going to address the underlying user need with Central's entity mechanism. I think it is -- a lot of people do script these kinds of updates and a lot more would if we felt comfortable sharing examples. Yes, we have plans for more entities features but they're going to take a bit and scripting updates satisfies a need now. It's also what people are used to from Aggregate and other systems.

We run into the bad state described in this issue because Central requires a form version change when changing form attachments. I think the idea was to be able to reconstruct exactly the state of the form when it was filled out. In practice, Central does save form attachments for every version but doesn't currently make them accessible for edits (only available through the API).

Some possible ways to address the issue:
- introduce a mechanism to overwrite form attachments for a published form version, maybe just through the API. This would solve all problems related to scripting form attachment updates. The only downside is that it would be impossible to reconstruct what a user saw when they were filling out a form.
- add a level of indirection representing a schema. Central could detect a form update that doesn't involve a form schema update and not store the form fields again. This would solve issues related to form fields. It does not address a related issue which is that the blobs table gets really full of all the form attachment versions.
- look into indexes and making the trigger more performant. I think we should do this regardless. Same as above, it doesn't address the blobs table getting big.

**Comment by ktuite** [comment]
We're choosing the indirect representation approach:
* When new defs come in, compare only to latest schema (walk through the fields and if there are any differences, make a new schema)
* Migration to collapse existing duplicate schemas

**Comment by lognaturel** [comment]
> introduce a mechanism to overwrite form attachments for a published form version

We're going to separate this out from the short-term bug fix.

@sadiqkhoja brought up that being able to overwrite published form attachments might be valuable beyond CSVs

@issa-tseng brought up a number of considerations:
1. there are questions around how this would interact with an existing draft
1. there's value to separating out editable and published states that we might miss for reasons we can't yet anticipate
1. there's clearly overlap with entities and there's confusion and overhead involved when there are many ways to do nearly the same thing

For 2 and 3 above, I think we just need to decide whether the risks are worth it.

For 1, we'd have to come up with a reasonable answer for what to do if there is a draft.

Currently, if a new draft is created programmatically, any existing draft is closed. This could be very confusing for someone trying to create a draft and possibly could lead to losing some state of a form definition or attachment that only exists in that draft. It's also relatively easy to explain and my experience is that the person/people scripting updates are also the ones most likely to be making manual form updates. Given that experience, I think it would be most predictable and easiest to explain if updating a published form attachment closed any existing draft. @issa-tseng points out that the current behavior is bad and could use rethinking.

We also discussed that the draft could "win" and overwrite a form attachment that was updated after the draft was created.

@issa-tseng also mentioned that there may be a big change coming to drafts that may touch on all of this.

**Comment by ktuite** [comment]
For changing the database schema to support an intermediate form schema that doesn't get needlessly duplicated, how does this sound?

Make a new a `form_schemas` table with `id` (and probably `formId`)
then `form_fields` could have a `formSchemaId` column instead of `formDefId`
and `form_defs` could have a new `formSchemaId` column

**Comment by sadiqkhoja** [comment]
> For changing the database schema to support an intermediate form schema that doesn't get needlessly duplicated, how does this sound?
> 
> Make a new a `form_schemas` table with `id` (and probably `formId`) then `form_fields` could have a `formSchemaId` column instead of `formDefId` and `form_defs` could have a new `formSchemaId` column

Looks good. But I don't see the need of `formId` in `form_schemas` table
