### ISSUE TITLE
Bug about not always using the right form def fields

### ISSUE THREAD

**Issue by ktuite** [getodk/central-backend#686]
I noticed this situation where I had uploaded an entity form, created a submission, but then rolled back all the dataset/entity database migrations and reapplied them, leaving empty dataset and entity tables.

When I republished the form to reinitialize the dataset, I tried approving an old submission for the *previous* version of the form.
To my surprise, it made an entity, even though that submission was linked to an earlier version of the form that no longer had any datasets or dataset fields associated with it. I've recreated that situation in the following test.

I'm thinking the query in `Datasets.getFieldsByFormDefId` is too liberal - I wanted to get the dataset property fields and the entity meta-data fields which may not be dataset properties, but in trying to do that, the joins are probably wrong and the fields for the wrong form version are also coming through.

```js
  it.only('should test out this weird case i saw', testService(async (service, container) => {
    await service.login('alice', (asAlice) =>
      asAlice.post('/v1/projects/1/forms?publish=true')
        .send(testData.forms.simpleEntity)
        .set('Content-Type', 'application/xml')
        .expect(200)
        .then(() => asAlice.post('/v1/projects/1/forms/simpleEntity/submissions')
          .send(testData.instances.simpleEntity.one)
          .set('Content-Type', 'application/xml')
          .expect(200)));

    // delete all the dataset stuff
    await container.run(sql`delete from dataset_form_defs`);
    await container.run(sql`delete from ds_property_fields`);
    await container.run(sql`delete from ds_properties`);
    await container.run(sql`delete from datasets`);

    // re-draft and re-publish the form
    await service.login('alice', (asAlice) =>
      asAlice.post('/v1/projects/1/forms/simpleEntity/draft')
        .expect(200));

    // dataset should come back, even as a draft
    const { count } = await container.one(sql`select count(*) from datasets`);
    count.should.equal(1);

    await service.login('alice', (asAlice) =>
      asAlice.post('/v1/projects/1/forms/simpleEntity/draft/publish?version=new')
        .expect(200)
        .then(() => asAlice.patch('/v1/projects/1/forms/simpleEntity/submissions/one')
          .send({ reviewState: 'approved' })
          .expect(200)));

    const forms = await container.all(sql`select "id", "xmlFormId" from forms`);
    // eslint-disable-next-line no-console
    console.log(forms);

    const row = await container.all(sql`select "id", "formId", "version", "createdAt", "publishedAt" from form_defs`);
    // eslint-disable-next-line no-console
    console.log(row);

    await exhaust(container);

    // this should NOT create an entity because the submission is for a form that had all
    // of its dataset information stripped away.
    const createEvent = await container.Audits.getLatestByAction('entity.create');
    // eslint-disable-next-line no-console
    console.log(createEvent);
  }));
```

**Comment by matthew-white** [comment]
I took a quick look at `Datasets.getFieldsByFormDefId()`. It seems to filter on `form_fields."formDefId"` correctly, which I think means that it's not pulling in fields from a different form def (🎉). I think what's happening is that the query will always return the form def's `/meta/entity` fields, assuming that those can't exist without there being an associated dataset. That seems like a pretty fair assumption. The only way that wouldn't be the case is if a user uploaded a form def with a `/meta/entity` field in a version of Central that doesn't support entities, then upgraded to a version that does support entities. Actually, I imagine that as entity-creating forms start circulating, that will become a real possibility. A user might upload an entity-creating form in an older version of Central, causing them to realize that entities aren't supported, which leads them to upgrade Central.

The query left-joins with `ds_property_fields` and `ds_properties`, which makes sense, but I'm thinking that it should inner-join with some dataset-related table in order to verify that the form def is associated with a dataset. Could the query just inner-join with `dataset_form_defs`? It seems to me like the only way a form def could have a corresponding `dataset_form_defs` record is if the form def was created in a version of Central that support entities.
