### ISSUE TITLE
Bulk entity CSV update

### ISSUE THREAD

**Issue by ktuite** [getodk/central-backend#804]
Allow entities to be created and updated via CSV!

**Comment by matthew-white** [comment]
I'm going to go ahead and close this issue, since we will be tracking this feature set through other issues. We will be working on bulk entity creation via CSV in v2024.1. At the moment, it looks like Backend won't be the one to process the CSV: Frontend will. Bulk update will likely come in a later release and will be associated with its own issue(s).
