### ISSUE TITLE
Revisit an entity's "source"

### ISSUE THREAD

**Issue by ktuite** [getodk/central-backend#819]
Plan as of April 5:

Store creatorId and userAgent on entity def.

Store as many details as necessary in audit log on `entity.create` or `entity.update` event. That would include entity uuid, entity def id (or entity def version), and details like whether it was an api request or bulk file upload.

**Comment by matthew-white** [comment]
For an `entity.update` event, Frontend will need to have some way to connect the event to the associated diff. Maybe that's a reason to store the entity def version number, not just the internal entity def id.

**Comment by matthew-white** [comment]
> For an `entity.update` event, Frontend will need to have some way to connect the event to the associated diff.

As discussed in #828, Frontend will be able to connect the event to the diff based on the order.

**Comment by matthew-white** [comment]
@ktuite and I chatted a little about the entity source today, and I wanted to mention two takeaways from that conversation.

**Takeaway 1: We need to save information about purged submissions**

We don't support individual submission deletion yet, but we do support form deletion. That means that a submission that created an entity can be soft-deleted (its form is in the trash), or it can be purged. When a form is purged, its name is saved in the `actees` table (in the `purgedName` column). We don't save information about a purged form's submissions. (That's mostly a good thing, because submission data can be PII.)

However, if an entity was created from a submission that has been deleted or purged, the release criteria call for showing the submission's instance ID. That means that if a submission created an entity, we need to save its instance ID somewhere if/when its form is purged. Because submissions aren't actees, that would probably have to be somewhere outside the `actees` table.

In the release criteria, I've also suggested that we show the name of the submission's form. Whether or not we decide to do that, that makes me think that when we save the instance ID of a purged submission, we should save alongside it the `acteeId` of its purged form. An instance ID by itself doesn't actually identify a submission: you also need to know its form. The form's `acteeId` would link to information about the purged form.

**Takeaway 2: Frontend needs to know the source of the root version**

The release criteria call for showing the instance name or ID of the "creating submission". I know we're planning to return the source of the current entity version in the entity response. However, I think what Frontend actually needs is the source of the root version. I don't think Frontend needs other information from the root version, so one option might be to add a top-level `source` property to the entity response to indicate the source of the root version (the source of the entity itself).

Frontend shows information about the creating submission in two places: the Basic Information section of the entity detail page and the entity activity feed. However, I'm happy to grab that information from one response and use it in multiple places on the entity detail page. For example, as long as the entity response includes the source of the root version, I don't think we need to store that information in the audit log as well (at least not for Frontend's sake).

**Comment by matthew-white** [comment]
#846 returns all the information that Frontend needs about the entity's source. I think it also addresses the two takeaways above.

Even if a submission is deleted or purged, its instance ID remains in the audit log. The actee ID of its form can also be found in the audit log. (I believe the form is the actee of submission events.)

I think we still have work to do for this issue. For example, we need to account for deleted submissions when returning the `source` property of an entity version. However, that would only be for the API: Frontend now has what it needs. Could we maybe get away with not returning a `source` property at all for .3, then come back to it when we work on CSV upload?
