### ISSUE TITLE
Remove entity label from audit log

### ISSUE THREAD

**Issue by matthew-white** [getodk/central-backend#822]
I don't think we need to make any changes right away, but as we start thinking about deleting and purging entities, I think we should think about what information about an entity should remain in the audit log even after the entity is deleted and purged. We should store the entity UUID and dataset name, but I think we should remove any entity data, including the entity label, because that information could be sensitive. Ideally, we don't log any of that information in the audit log to begin with.

We currently log the entity label as part of the details of the `entity.create` event. Frontend uses the entity label on the submission detail page, so if we remove it from the details of the audit log entry, we'll need to figure out how to get that information to Frontend.

Update from Kathleen:
Backend PR: https://github.com/getodk/central-backend/pull/959
Frontend PR: https://github.com/getodk/central-frontend/pull/850

**Comment by ktuite** [comment]
How to test this issue: 

For a submission that creates an entity, this event on the submission activity feed should look the same as before and have a working link

![Image](https://github.com/getodk/central-backend/assets/76205/f9009171-0561-477f-a291-bb956b864666)

Unless the entity has been deleted (soft-deleted with the API), in which case it should show the entity's UUID instead and not be a link (because the link wont go to a valid page).

**Comment by dbemke** [comment]
**Tested with success!**

**Comment by srujner** [comment]
Tested with success!
