### ISSUE TITLE
Fix sending usage metrics problem

### ISSUE THREAD

**Issue by ktuite** [getodk/central-backend#970]
Running `node lib/bin/run-analytics.js` (or the docker production equivalent) doesn't work. It hangs for many seconds and then returns this error:

```
'{"sent":false,"message":"Error submitting analytics","error":{"code":"ECONNRESET"}}'
```

Likely something in `external/odk-analytics.js` with how streaming responses get sent. Checking specficially on `FormData` which is now built into Node 18 but doesn't seem to work the same way. 

Even on staging, sending analytics has been broken for a while. Matt said on slack:

> https://staging.getodk.cloud/v1/audits?action=analytics is interesting. A report was sent on July 27, but it’s been failing since Aug 27. Presumably something changed in that month.

**Comment by matthew-white** [comment]
If I understand correctly, I think `FormData` is being used in order to send the submission XML as a file to the OpenRosa submission endpoint. I think we could:

- Change how we use `FormData` to match the expectations of Node 18. There are just a few calls involving `FormData`, so maybe this wouldn't be a big change?
- Alternatively: do we even need to use `FormData`? I think we could submit to the REST endpoint instead of the OpenRosa endpoint. Then we could just send the XML as the request body rather than sending a file.
